INSERT INTO Course (name, level) VALUES ('Math', '102')
INSERT INTO Course (name, level) VALUES ('Math', '112')
INSERT INTO Course (name, level) VALUES ('Math', '122')
INSERT INTO Course (name, level) VALUES ('English', '102')
INSERT INTO Course (name, level) VALUES ('English', '112')
INSERT INTO Course (name, level) VALUES ('English', '122')
INSERT INTO Course (name, level) VALUES ('French', '102')
INSERT INTO Course (name, level) VALUES ('French', '112')
INSERT INTO Course (name, level) VALUES ('French', '122')
INSERT INTO Course (name, level) VALUES ('Biology', '102')
INSERT INTO Course (name, level) VALUES ('Biology', '112')
INSERT INTO Course (name, level) VALUES ('Biology', '122')
INSERT INTO Course (name, level) VALUES ('Chemistry', '102')
INSERT INTO Course (name, level) VALUES ('Chemistry', '112')
INSERT INTO Course (name, level) VALUES ('Chemistry', '122')
INSERT INTO Course (name, level) VALUES ('Physics', '102')
INSERT INTO Course (name, level) VALUES ('Physics', '112')
INSERT INTO Course (name, level) VALUES ('Physics', '122')
INSERT INTO Course (name, level) VALUES ('Computer Science', '102')
INSERT INTO Course (name, level) VALUES ('Computer Science', '112')
INSERT INTO Course (name, level) VALUES ('Computer Science', '122')
