<?xml version="1.0" encoding="utf-8"?><Database Name="RHSCodingClub02" Class="RHSCodingClubDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=RHSCodingClub02;Integrated Security=True;Connect Timeout=30" SettingsObjectName="RHSCodingClub02.Properties.Settings" SettingsPropertyName="RHSCodingClub02ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isDeleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[level]" Member="level" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="isDeleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StudentCourse" Member="StudentCourses">
    <Type Name="StudentCourse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="courseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="finalGrade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isDeleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>